name: new_bakarbatu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

#  Service Locator
  get_it: ^7.2.0
#  State management
  flutter_bloc: ^8.1.1
#  Value Equality
  equatable: ^2.0.5
#  Functional Programming thingies
  dartz: ^0.10.1
#  Remote API
  connectivity_plus: ^3.0.2
  http: ^0.13.5
  dio: ^4.0.6
#  Local cache and database
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
# WebView
  flutter_inappwebview: ^5.7.1
  url_launcher: ^6.1.6
# floating action button
  custom_floating_action_button: ^0.0.3
# Caemra utilities
  image_picker: ^0.8.6
  video_player: ^2.4.7
  chewie: ^1.3.5
  video_compress: ^3.1.1
# Record Audio
  flutter_audio_recorder2: ^0.0.2
  path_provider: ^2.0.11
  audioplayers: ^1.1.1
# Icon APP
  flutter_launcher_icons: ^0.10.0
# Datepicker
  date_time_picker: ^2.1.0
# Loading UI
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  image_downloader: ^0.31.0
  flutter_svg: ^1.1.6

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/app_icon/logo.png"
  image_path_ios: "assets/app_icon/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
#  To Testing
  mockito: ^5.3.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
